app:
  name: wallet-service
  env: local

http:
  port: 8080

db:
  dsn: postgresql://usr_wallet_rw:dsf43mlSHGRcsfs@postgresql.homelab.services:5432/wallet_db?sslmode=disable
  maxconns: 30
  minconns: 10